import type {
  CycleSummary,
  DashboardStats,
  DirectivePayload,
  BootstrapStatusPayload,
  DiscoveryPayload,
  ExperienceEntry,
  LlmAuditEntry,
  ModelRegistryPayload,
  TaskDetail,
  TaskEvent,
  TaskSummary,
  ThreadDetail,
  ThreadSummary,
} from '../types/dashboard'

/** HTTP client dedicated to dashboard backend APIs. */
export class DashboardApiClient {
  private readonly baseUrl: string

  /** Create client with optional base URL prefix. */
  constructor(baseUrl = '') {
    this.baseUrl = baseUrl
  }

  /** Execute one JSON request and throw contextual errors when it fails. */
  private async requestJson<T>(path: string, init?: RequestInit): Promise<T> {
    const response = await fetch(`${this.baseUrl}${path}`, init)
    if (!response.ok) {
      throw new Error(`Request failed (${response.status}) for ${path}`)
    }
    return (await response.json()) as T
  }

  /** Fetch task summary list. */
  getTasks(): Promise<{ updated_at: string; tasks: TaskSummary[] }> {
    return this.requestJson('/api/tasks')
  }

  /** Fetch one task detail and its event timeline. */
  getTaskDetail(taskId: string): Promise<{ task?: TaskDetail; events?: TaskEvent[]; error?: string }> {
    return this.requestJson(`/api/tasks/${encodeURIComponent(taskId)}`)
  }

  /** Fetch latest cycle summary rows. */
  getCycles(): Promise<{ cycles: CycleSummary[] }> {
    return this.requestJson('/api/cycles')
  }

  /** Fetch aggregate dashboard counters. */
  getStats(): Promise<DashboardStats> {
    return this.requestJson('/api/stats')
  }

  /** Fetch current runtime directive. */
  getDirective(): Promise<DirectivePayload> {
    return this.requestJson('/api/directive')
  }

  /** Pause the agent immediately. */
  pause(): Promise<{ status: string; paused: boolean }> {
    return this.requestJson('/api/pause', { method: 'POST' })
  }

  /** Resume the agent immediately. */
  resume(): Promise<{ status: string; paused: boolean }> {
    return this.requestJson('/api/resume', { method: 'POST' })
  }

  /** Persist directive updates from control panel form. */
  saveDirective(payload: DirectivePayload): Promise<{ status: string; directive: DirectivePayload }> {
    return this.requestJson('/api/directive', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    })
  }

  /** Create a manual task from dashboard inject form. */
  injectTask(payload: {
    title: string
    description: string
    priority: number
  }): Promise<{ status?: string; task_id?: string; error?: string }> {
    return this.requestJson('/api/tasks/inject', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    })
  }

  /** Fetch recent activity stream events. */
  getActivity(limit = 250, module = ''): Promise<{ events: Record<string, unknown>[]; total_returned: number }> {
    const query = module ? `?limit=${limit}&module=${encodeURIComponent(module)}` : `?limit=${limit}`
    return this.requestJson(`/api/activity${query}`)
  }

  /** Fetch the dashboard discovery projection derived from observer activity. */
  getDiscovery(limit = 50): Promise<DiscoveryPayload> {
    return this.requestJson(`/api/discovery?limit=${limit}`)
  }

  /** Fetch recent audit list for LLM calls. */
  getLlmAudit(limit = 100): Promise<{ entries: LlmAuditEntry[]; total_returned: number }> {
    return this.requestJson(`/api/llm-audit?limit=${limit}`)
  }

  /** Fetch one full LLM audit record. */
  getLlmAuditDetail(seq: number): Promise<{ entry?: Record<string, unknown>; error?: string }> {
    return this.requestJson(`/api/llm-audit/${seq}`)
  }

  /** Fetch unresolved human-help requests generated by the agent. */
  getHelpCenter(): Promise<{ updated_at: string; requests: TaskSummary[] }> {
    return this.requestJson('/api/help-center')
  }

  /** Mark one help-center request resolved so agent can continue verification. */
  resolveHelpRequest(payload: {
    task_id: string
    resolution?: string
  }): Promise<{ status?: string; task_id?: string; next_status?: string; error?: string }> {
    return this.requestJson('/api/help-center/resolve', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    })
  }

  /** Fetch persisted experience memory entries for dashboard review. */
  getExperiences(limit = 100): Promise<{ updated_at: string; total: number; experiences: ExperienceEntry[] }> {
    return this.requestJson(`/api/experiences?limit=${limit}`)
  }

  /** Fetch model registry state and runtime binding metadata. */
  getModels(): Promise<ModelRegistryPayload> {
    return this.requestJson('/api/models')
  }

  /** Fetch startup readiness for setup flow. */
  getBootstrapStatus(): Promise<BootstrapStatusPayload> {
    return this.requestJson('/api/bootstrap-status')
  }

  /** Register one model for later runtime binding. */
  registerModel(payload: {
    model_type: 'llm' | 'embedding'
    base_url: string
    api_path: string
    model_name: string
    api_key: string
    desc: string
  }): Promise<{ status?: string; model?: Record<string, unknown>; error?: string }> {
    return this.requestJson('/api/models', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    })
  }

  /** Update one existing registered model. Blank api_key keeps the stored secret. */
  updateModel(modelId: string, payload: {
    model_type: 'llm' | 'embedding'
    base_url: string
    api_path: string
    model_name: string
    api_key: string
    desc: string
  }): Promise<{ status?: string; model?: Record<string, unknown>; error?: string }> {
    return this.requestJson(`/api/models/${encodeURIComponent(modelId)}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    })
  }

  /** Delete one registered model and clear bindings that point at it. */
  deleteModel(modelId: string): Promise<{ status?: string; model_id?: string; error?: string }> {
    return this.requestJson(`/api/models/${encodeURIComponent(modelId)}`, {
      method: 'DELETE',
    })
  }

  /** Persist selected model ids for runtime binding points. */
  saveModelBindings(payload: {
    bindings: Record<string, string>
  }): Promise<{ status?: string; bindings?: Record<string, { model_id: string; updated_at?: string }>; error?: string }> {
    return this.requestJson('/api/model-bindings', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    })
  }

  /** List threads, optionally filtered by status. */
  getThreads(status?: string): Promise<{ threads: ThreadSummary[]; total: number }> {
    const query = status ? `?status=${encodeURIComponent(status)}` : ''
    return this.requestJson(`/api/threads${query}`)
  }

  /** Fetch one thread with messages and linked task ids. */
  getThreadDetail(threadId: string): Promise<ThreadDetail & { error?: string }> {
    return this.requestJson(`/api/threads/${encodeURIComponent(threadId)}`)
  }

  /** Post a human reply to an existing thread. */
  replyToThread(threadId: string, body: string): Promise<{ status?: string; thread_id?: string; error?: string }> {
    return this.requestJson(`/api/threads/${encodeURIComponent(threadId)}/reply`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ body }),
    })
  }

  /** Human creates a new thread (Shape B) — also queues a task. */
  createThread(payload: {
    title: string
    description?: string
    priority?: number
  }): Promise<{ status?: string; thread_id?: string; task_id?: string; error?: string }> {
    return this.requestJson('/api/threads', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    })
  }

  /** Human closes a thread; linked tasks in NEEDS_HUMAN/QUEUED are moved to FAILED. */
  closeThread(threadId: string, reason: string): Promise<{ status?: string; thread_id?: string; error?: string }> {
    return this.requestJson(`/api/threads/${encodeURIComponent(threadId)}/close`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ reason }),
    })
  }

  /** Bulk-close a list of threads. */
  bulkCloseThreads(threadIds: string[]): Promise<{ closed?: number; error?: string }> {
    return this.requestJson('/api/threads/bulk-close', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ thread_ids: threadIds }),
    })
  }
}

/** Singleton client used by dashboard UI screens. */
export const dashboardApiClient = new DashboardApiClient('')
